const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 40,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      name: 'Fuck Shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 35,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Fuck Shirt',
    },
    {
      name: 'Cock Shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 30,
      brand: 'Adidas',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Cock Shirt',
    },
    {
      name: 'Cock Pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 35,
      brand: 'Adidas',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Cock pair of pants',
    },
    {
      name: 'Shit Pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 50,
      brand: 'Nike',
      rating: 3.4,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shit pair of pants',
    },
    {
      name: 'Cunt Pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 76,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Cunt pair of pants',
    },
  ],
};

export default data;
