const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 40,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      name: 'Nice Shirt',
      slug: 'nice-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 35,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular nice Shirt',
    },
    {
      name: 'Rock Shirt',
      slug: 'rock-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 30,
      brand: 'Adidas',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Rock Shirt',
    },
    {
      name: 'Rock Pants',
      slug: 'rock-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 35,
      brand: 'Adidas',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular rock pair of pants',
    },
    {
      name: 'Hike Pants',
      slug: 'hike-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 50,
      brand: 'Nike',
      rating: 3.4,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pair of pants',
    },
    {
      name: 'Sexy Pants',
      slug: 'sexy-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 76,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 10,
      countInStock: 0,
      description: 'A popular pair of sexy pants',
    },
  ],
};

export default data;
